name: sample
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  cached_network_image: ^2.0.0
  tab_scaffold: ^0.1.0
  image_picker: ^0.6.3+1
  firebase_analytics: ^5.0.11
  post_repository:
    path: post_repository
  user_repository:
    path: user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
